baseURL = "/"
languageCode = "en-us"
title = "Gloo Core Documentation"
linkTitle = "Docs"
contentDir = "content/en/gloo-gateway"

[module]
    # uncomment "replacements" line below for temporary local development of module,
    # when using a 'theme' as a git submodule or git cloned files
    # replacements = "github.com/solo-io/docs-theme-lotus -> docs-theme-lotus"
    [[module.imports]]
        path = "../.."
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[params]

buildCondition = "core"
# google_font = ["Proxima Nova:300,300i,400,400i,700,700i"]
mono_font = "Courier"
pathName = "/gloo-gateway/docs"
version = "main"

[params.footer]

copyright = "Solo.io copyright 2023"

[params.social]

github = "solo-io"
twitter = "soloio_inc"

[params.docs]

title = "Solo.io documentation"
themeColor = "blue"
prism = true
darkMode = true
breadcrumbs = true
descriptions = true
backToTop = true
sidebarIcons = true
titleIcon = false
lastMod = true
scrollspy = true
navDesc = true
ghrepo = "github.com/solo-io/docs-theme-lotus"
editPage = true
toc = true


[params.flexsearch]

enabled = true
tokenize            = "full" # default is "forward"
cache               = 100    # default is 100
optimize            = true   # default is true
minQueryChar        = 3      # default is 0 (disabled)
maxResult           = 5      # default is 5
searchSectionsIndex = []

[params.versionInfo]
  dropdownMenuText = "Release version" # Can be used to show instead of the version - NOT IMPLEMENTED IN OUR ENVIRONMENT
  archived = false                     # indicate this is an archived doc set branch and display warning banner - NOT IMPLEMENTED YET
  unreleased = false                   # indicate this is an unreleased doc set branch and display warning banner - NOT IMPLEMENTED YET

[[params.versions]]
  version = "main"
  linkVersion = "main"
  url = "https://docs.solo.io/gloo-mesh-core/main/"
[[params.versions.subversions]]
  id = "v1"
  label = "Version 1"
[[params.versions.subversions]]
  id = "v4"
  label = "Version 4"

[[params.versions]]
  version = "2.5 (latest)"
  linkVersion = "latest"
  url = "https://docs.solo.io/gloo-mesh-core/latest/"

[markup]

[markup.tableOfContents]

endLevel = '6'
startLevel = '1'

[markup.goldmark.renderer]

unsafe = true
